include_openerp_py_new_api:
  ctx: 'final or migrate_multi'
  include: 'openerp_py_new_api'
include_odoo_api_multi:
  ctx: 'final'
  include: 'odoo_py_api_multi'
class_product_uom:
  match: '.*(?<!\w)UomUom(?!\w)'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'UomUom'
      - 'ProductUom'
product_uom:
  match: '.*["'']uom\.uom["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'uom.uom'
      - 'product.uom'
product_uom_unit:
  match: '.*["'']uom\.product_uom_unit["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'uom.product_uom_unit'
      - 'product.product_uom_unit'
class_product_uom_category:
  match: '.*(?<!\w)UomCategory(?!\w)'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'UomCategory'
      - 'ProductUomCateg'
product_uom_category:
  match: '.*["'']uom\.category["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'uom.category'
      - 'product.uom.categ'
product_uom_categ_unit:
  match: '.*["'']uom\.product_uom_categ_unit["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'uom.product_uom_categ_unit'
      - 'product.product_uom_categ_unit'
stock_rule:
  match: '.*["'']stock\.rule["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'stock.rule'
      - 'procurement.rule'
import_oerplib:
  match: '^ *import oerplib3 as oerplib'
  prio: '9'
  do:
    - action: 's'
      args:
      - import oerplib3 as oerplib
      - import oerplib
oerplib3:
  match: '.*["'']oerplib3["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - oerplib3
      - oerplib
product_uom_form_view:
  match: '.*["'']uom.product_uom_form_view["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'uom.product_uom_form_view'
      - 'product.product_uom_form_view'
MailDeliveryException:
  match: 'from odoo.*MailDeliveryException'
  prio: '9'
  do:
    - action: 's'
      args:
      - odoo.addons.base.models.ir_mail_server
      - odoo.addons.base.ir.ir_mail_server
