include_odoo_py_new_api:
  ctx: 'final'
  include: 'odoo_py_new_api'
include_odoo_api_multi:
  ctx: 'final or backport_multi'
  include: 'odoo_py_api_multi'
sort_from_odoo_import:
  match: '^from (odoo|openerp) import [\w, ]+'
  prio: '9'
  do:
    - action: '$'
      args:
      - 'sort_from_odoo_import'
class_product_uom:
  match: '.*(?<!\w)ProductUom(?!\w)'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'ProductUom'
      - 'UomUom'
product_uom:
  match: '.*["'']product\.uom["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'product.uom'
      - 'uom.uom'
product_uom_unit:
  match: '.*["'']product\.product_uom_unit["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'product.product_uom_unit'
      - 'uom.product_uom_unit'
class_product_uom_category:
  match: '.*(?<!\w)ProductUomCateg(?!\w)'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'ProductUomCateg'
      - 'UomCategory'
product_uom_category:
  match: '.*["'']product\.uom\.categ["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'product.uom.categ'
      - 'uom.category'
product_uom_categ_unit:
  match: '.*["'']product\.product_uom_categ_unit["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'product.product_uom_categ_unit'
      - 'uom.product_uom_categ_unit'
stock_rule:
  match: '.*["'']procurement\.rule["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'procurement.rule'
      - 'stock.rule'
product_uom_form_view:
  match: '.*["'']product.product_uom_form_view["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'product.product_uom_form_view'
      - 'uom.product_uom_form_view'
      -
MailDeliveryException:
  match: 'from odoo.*MailDeliveryException'
  prio: '9'
  do:
    - action: 's'
      args:
      - odoo.addons.base.ir.ir_mail_server
      - odoo.addons.base.models.ir_mail_server
