# This configuration is loaded for .py files in Odoo product
# when organization is "zero" and Odoo version is 10.0
#
module_l10n_it_fatturapa_out:
  match: '.*["'']l10n_it_fatturapa_out["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'l10n_it_fatturapa_out'
      - 'l10n_it_einvoice_out'
module_l10n_it_account_stamp:
  match: '.*["'']l10n_it_account_stamp["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'l10n_it_account_stamp'
      - 'l10n_it_einvoice_stamp'
model_sdi_channel:
  match: '.*["'']sdi.channel["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'sdi.channel'
      - 'italy.ade.sender'
sdi_channel_id:
  match: '.*(?<!\w)sdi_channel_id(?!\w)'
  prio: '9'
  do:
    - action: 's'
      args:
        - sdi_channel_id
        - einvoice_sender_id
def_send_to_sdi:
  match: '.*(?<!\w)send_to_sdi(?!\w)'
  prio: '9'
  do:
    - action: 's'
      args:
      - send_to_sdi
      - send_verify
def_get_sdi_channel:
  match: '.*(?<!\w)get_send_channel(?!\w)'
  prio: '9'
  do:
    - action: 's'
      args:
        - get_send_channel
        - get_sdi_channel
state_subtype_mapping:
  match: '.*(?<!\w)evolve_stato_mapping(?!\w)'
  prio: '9'
  do:
    - action: 's'
      args:
        - evolve_stato_mapping
        - STATE_SUBTYPE_MAPPING
