# Odoo yaml template for travis-ci
# __version__=2.0.14

language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  # For branches <= 10.0, put `- "2.7"`
  - "3.5"
  - "3.6"
  - "3.7"

virtualenv:
  system_site_packages: false

git:
  submodules: false
  depth: false

services:
  - postgresql

addons:
  # postgresql: "9.5"
  apt:
    sources:
    # Search your sources alias here:
    # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
      - pov-wkhtmltopdf
    packages:
      # - build-essential                 # Pre-installed
      # - curl                            # Pre-installed
      - expect-dev
      # - less-plugin-clean-css           # Pre-installed
      # - lessc                           # Pre-installed
      - libevent-dev
      - libffi-dev
      - libssl-dev
      # - nodejs                          # Pre-installed
      # - npm                             # Pre-installed
      - python-dev
      # - python-setuptools               # Pre-installed
      # - wkhtmltopdf                     # Pre-installed
      - zlib1g

before_install:
  # Use ZeroincombenzeÂ® tools
  - git clone https://github.com/zeroincombenze/tools.git ${HOME}/tools --single-branch --depth=1
  - ${HOME}/tools/install_tools.sh -qpt
  - source ${HOME}/devel/activate_tools
  # Sometimes complicated website repos need Compass & SaSS:
  #  - rvm install ruby --latest
  #  - gem install bootstrap-sass
  #  - gem install compass --pre
  #  OCB
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  # - sleep 3 # give xvfb some time to start

install:
  - travis_install_env
  - export EXCLUDE=hw_scanner,hw_escpos,document_ftp,delivery,stock_invoice_directly,claim_from_delivery,theme_bootswatch
  - export INCLUDE=$(getaddons.py -m ${HOME}/build/${ODOO_REPO}/odoo/addons ${HOME}/build/${ODOO_REPO}/addons)

env:
  global:
  - TRAVIS_DEBUG_MODE="2"
  - VERSION="${TRAVIS_BRANCH}" TESTS="0" LINT_CHECK="0" ODOO_TNLBOT="0 ODOO_REPO="${TRAVIS_REPO_SLUG}"
  # Set this variable to some version existing as linux-generic build on
  # https://github.com/wkhtmltopdf/wkhtmltopdf/releases
  # if you need to install wkhtmltopdf
  - WKHTMLTOPDF_VERSION="0.12.5"
  # Set the above to install a `wkhtmltopdf` version that is not the one provided
  # by the `pov-wkhtmltopdf` repo.
  - PHANTOMJS_VERSION="latest"
  # The above line controls the PhantomJS version that is used for JS testing.
  #   It is not necessary to include this value unless you are altering the default.
  #   Use `OS` to skip the PhantomJS upgrade & use the system version instead.
  - WEBSITE_REPO="1"
  # Use the above line to install dependencies that are required for website repos:
  # * SASS & Bootstrap-SASS
  # * Compass

  matrix:
  - LINT_CHECK="1"
# use this to install a standalone database to export .pot files
# - MAKEPOT="1"
# add MAKEPOT="1" to a TEST line to export .pot files from
# the test database after test success
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="zeroincombenze/OCB"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="zeroincombenze/OCB" UNIT_TEST="1"

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success





